version: "3.8"

services:
  api-server-1:
    container_name: "api-exemple-rlc-1"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
    networks:
      - express_network

  api-server-2:
    container_name: "api-exemple-rlc-2"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
    networks:
      - express_network

  redis:
    container_name: "redis-rlc"
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - express_network

  nginx:
    container_name: "nginx-rlc"
    image: nginx:1.21.6
    ports:
      - "7777:80"
    volumes:
      - ./exemples/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - redis
      - api-server-1
      - api-server-2
    networks:
      - express_network

networks:
  express_network:
    driver: bridge
